// Behavioral MCP tests for df_skills_install + df_skills_list (DFP #192).
//
// Drives the MCP server end-to-end through the SDK's InMemoryTransport
// pair (same pattern as handoff.test.ts) so we exercise the JSON-RPC
// framing + the structured content envelope. The tool wraps the same
// `installSkill` / `listBundledSkills` core that the CLI subcommand
// uses, so deep behavioral coverage of the install logic lives in
// tests/skills/install.test.ts — these tests pin the MCP-surface contract
// (input/output schemas, isError on bad args, structuredContent shape).

import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { afterEach, beforeEach, describe, expect, it } from "vitest";

import { registerSkillsTools } from "../../../src/mcp/tools/skills-install.js";

interface ToolResult {
  content?: unknown;
  isError?: boolean;
  structuredContent?: unknown;
}

async function withSkillsMcp(
  cwd: string,
  testFn: (client: Client) => Promise<void>,
): Promise<void> {
  const server = new McpServer(
    { name: "df-skills-test/mcp", version: "0.0.0" },
    { capabilities: { tools: {} } },
  );
  registerSkillsTools(server, { cwd });

  const [clientTransport, serverTransport] =
    InMemoryTransport.createLinkedPair();
  await server.connect(serverTransport);

  const client = new Client(
    { name: "df-skills-test", version: "0.0.0" },
    { capabilities: {} },
  );
  await client.connect(clientTransport);

  try {
    await testFn(client);
  } finally {
    await client.close();
    await server.close();
  }
}

function firstText(result: ToolResult): string | undefined {
  const content = result.content as Array<{ type: string; text?: string }> | undefined;
  return content?.find((c) => c.type === "text")?.text;
}

describe("df_skills_install MCP tool", () => {
  let dir: string;
  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), "df-skills-mcp-"));
  });
  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it("happy path: installs a single named skill, returns structured envelope", async () => {
    await withSkillsMcp(dir, async (client) => {
      const result = (await client.callTool({
        name: "df_skills_install",
        arguments: { skillName: "chief-engineer-blitz" },
      })) as ToolResult;

      expect(result.isError).toBeFalsy();
      const structured = result.structuredContent as {
        installed: Array<{
          skillName: string;
          manifestVersion: string;
          configIsDefault: boolean;
          files: Array<{ relTarget: string; action: string }>;
        }>;
      };
      expect(structured.installed).toHaveLength(1);
      const first = structured.installed[0]!;
      expect(first.skillName).toBe("chief-engineer-blitz");
      expect(first.configIsDefault).toBe(true);
      expect(first.files.length).toBeGreaterThan(0);
      expect(first.files.every((f) => f.action === "created")).toBe(true);

      // Files actually landed on disk.
      const skillMd = join(dir, ".claude", "skills", "chief-engineer-blitz", "SKILL.md");
      expect(existsSync(skillMd)).toBe(true);
      const body = readFileSync(skillMd, "utf8");
      expect(body).toContain("GENERATED by `df skills install");
      expect(body).not.toMatch(/\{\{[A-Z][A-Z0-9_]*\}\}/);

      const text = firstText(result);
      expect(text).toMatch(/chief-engineer-blitz/);
    });
  });

  it("--all installs every skill declared enabled: true", async () => {
    writeFileSync(
      join(dir, "darkfactory.yaml"),
      `repo:
  displayName: "Test Repo"
skills:
  chief-engineer-review:
    enabled: true
  chief-engineer-blitz:
    enabled: true
`,
    );
    await withSkillsMcp(dir, async (client) => {
      const result = (await client.callTool({
        name: "df_skills_install",
        arguments: { all: true },
      })) as ToolResult;

      expect(result.isError).toBeFalsy();
      const structured = result.structuredContent as {
        installed: Array<{ skillName: string }>;
      };
      const installedNames = structured.installed.map((i) => i.skillName).sort();
      expect(installedNames).toEqual(["chief-engineer-blitz", "chief-engineer-review"]);
      expect(
        existsSync(join(dir, ".claude", "skills", "chief-engineer-blitz", "SKILL.md")),
      ).toBe(true);
      expect(
        existsSync(join(dir, ".claude", "skills", "chief-engineer-review", "SKILL.md")),
      ).toBe(true);
    });
  });

  it("error path: both skillName and all=true → isError + helpful message", async () => {
    await withSkillsMcp(dir, async (client) => {
      const result = (await client.callTool({
        name: "df_skills_install",
        arguments: { skillName: "chief-engineer-blitz", all: true },
      })) as ToolResult;
      expect(result.isError).toBe(true);
      expect(firstText(result)).toMatch(/cannot pass both/);
    });
  });

  it("error path: neither skillName nor all → isError + helpful message", async () => {
    await withSkillsMcp(dir, async (client) => {
      const result = (await client.callTool({
        name: "df_skills_install",
        arguments: {},
      })) as ToolResult;
      expect(result.isError).toBe(true);
      expect(firstText(result)).toMatch(/skillName is required/);
    });
  });

  it("error path: unknown skill name → isError", async () => {
    await withSkillsMcp(dir, async (client) => {
      const result = (await client.callTool({
        name: "df_skills_install",
        arguments: { skillName: "not-a-real-skill" },
      })) as ToolResult;
      expect(result.isError).toBe(true);
      expect(firstText(result)).toMatch(/unknown skill/);
    });
  });

  it("error path: all=true but no skills enabled → isError + actionable message", async () => {
    writeFileSync(
      join(dir, "darkfactory.yaml"),
      `skills:
  chief-engineer-blitz:
    enabled: false
`,
    );
    await withSkillsMcp(dir, async (client) => {
      const result = (await client.callTool({
        name: "df_skills_install",
        arguments: { all: true },
      })) as ToolResult;
      expect(result.isError).toBe(true);
      expect(firstText(result)).toMatch(/no skills marked enabled/);
    });
  });

  it("returns isError=true when any file is skipped (mirrors CLI exit-code 3 contract, finding 2)", async () => {
    // First install lands clean. Then we hand-edit one file (strip the
    // GENERATED marker) so a re-install treats it as hand-edited → skipped.
    // Expectation: MCP surfaces this as isError so the agent caller does
    // not silently accept a partial install.
    await withSkillsMcp(dir, async (client) => {
      const first = (await client.callTool({
        name: "df_skills_install",
        arguments: { skillName: "chief-engineer-blitz" },
      })) as ToolResult;
      expect(first.isError).toBeFalsy();

      const skillMd = join(dir, ".claude", "skills", "chief-engineer-blitz", "SKILL.md");
      const handEdited = readFileSync(skillMd, "utf8").replace(
        /<!--\s*\n\s+GENERATED by `df skills install [^]*?-->\n?/,
        "",
      );
      writeFileSync(skillMd, handEdited);

      const second = (await client.callTool({
        name: "df_skills_install",
        arguments: { skillName: "chief-engineer-blitz" },
      })) as ToolResult;
      expect(second.isError).toBe(true);
      const structured = second.structuredContent as {
        installed: Array<{ files: Array<{ action: string; reason?: string }> }>;
      };
      const skipped = structured.installed[0]!.files.find(
        (f) => f.action === "skipped",
      );
      expect(skipped).toBeDefined();
      expect(skipped?.reason).toBeDefined();
      // The text content should explain the skip + the --force remediation
      // so the agent has actionable next steps.
      const text = firstText(second);
      expect(text).toMatch(/skipp|hand-edit|force/i);
    });
  });

  it("respects consumer overrides from darkfactory.yaml", async () => {
    writeFileSync(
      join(dir, "darkfactory.yaml"),
      `repo:
  displayName: "Test Display Name"
qualityGates:
  - "make test-x"
`,
    );
    await withSkillsMcp(dir, async (client) => {
      const result = (await client.callTool({
        name: "df_skills_install",
        arguments: { skillName: "chief-engineer-review" },
      })) as ToolResult;
      expect(result.isError).toBeFalsy();
      const body = readFileSync(
        join(dir, ".claude", "skills", "chief-engineer-review", "SKILL.md"),
        "utf8",
      );
      expect(body).toContain("Test Display Name");
      expect(body).toMatch(/```bash\nmake test-x\n```/);
    });
  });
});

describe("df_skills_list MCP tool", () => {
  it("lists every bundled skill with version + summary", async () => {
    const tmp = mkdtempSync(join(tmpdir(), "df-list-"));
    try {
      await withSkillsMcp(tmp, async (client) => {
        const result = (await client.callTool({
          name: "df_skills_list",
          arguments: {},
        })) as ToolResult;
        expect(result.isError).toBeFalsy();
        const structured = result.structuredContent as {
          skills: Array<{ name: string; version: string; summary: string }>;
        };
        const names = structured.skills.map((s) => s.name);
        expect(names).toContain("chief-engineer-review");
        expect(names).toContain("chief-engineer-blitz");
        for (const item of structured.skills) {
          expect(item.summary.length).toBeGreaterThan(0);
          expect(item.version).toMatch(/^\d+\.\d+\.\d+/);
        }
      });
    } finally {
      rmSync(tmp, { recursive: true, force: true });
    }
  });
});
