// Integration tests for `installSkill` against the BUNDLED skills.
//
// This is the test that catches drift between:
//   - A new {{VAR}} reference in a .tmpl without a matching skill.json#variables entry
//   - A missing template file the manifest still lists
//   - A skill.json#name that doesn't match its directory
//
// We exercise the real bundled skills (chief-engineer-review +
// chief-engineer-blitz) against a temp consumer cwd + a synthetic
// darkfactory.yaml, then assert the rendered files contain (or don't
// contain) the expected substitutions.

import { existsSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, beforeEach, describe, expect, it } from "vitest";

import {
  installSkill,
  KNOWN_SKILLS,
  listBundledSkills,
  resolveSkillsRoot,
} from "../../src/skills/install.js";

describe("installSkill — bundled skills", () => {
  let dir: string;
  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), "df-install-"));
  });
  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it("installs every bundled skill against the manifest defaults (no darkfactory.yaml)", () => {
    for (const skillName of KNOWN_SKILLS) {
      const r = installSkill({ cwd: dir, skillName });
      expect(r.skillName).toBe(skillName);
      expect(r.configIsDefault).toBe(true);
      expect(r.files.every((f) => f.action === "created")).toBe(true);
      for (const f of r.files) {
        expect(existsSync(f.absoluteTarget)).toBe(true);
        const body = readFileSync(f.absoluteTarget, "utf8");
        expect(body).toContain("GENERATED by `df skills install");
        expect(body).toContain("install-hash:");
        // No unresolved {{VAR}} references should remain.
        expect(body).not.toMatch(/\{\{[A-Z][A-Z0-9_]*\}\}/);
      }
    }
  });

  it("renders consumer overrides into chief-engineer-review SKILL.md", () => {
    writeFileSync(
      join(dir, "darkfactory.yaml"),
      `repo:
  displayName: "Dark Factory Platform"
docs:
  manifesto: "docs/PRINCIPLES.md"
  adrDir: "docs/ADR"
  cycleDocsDir: "docs/roadmap/cycles"
agents:
  chiefEngineer: ".claude/agents/chief-engineer.md"
qualityGates:
  - "make quality-gates"
  - "make test"
`,
    );
    const r = installSkill({ cwd: dir, skillName: "chief-engineer-review" });
    expect(r.configIsDefault).toBe(false);
    const skillMdPath = r.files.find((f) => f.relTarget === "SKILL.md");
    expect(skillMdPath).toBeDefined();
    const body = readFileSync(skillMdPath!.absoluteTarget, "utf8");
    expect(body).toContain("AI-native architectural review system for Dark Factory Platform");
    expect(body).toContain("docs/PRINCIPLES.md");
    expect(body).toContain("docs/ADR/");
    expect(body).toContain("docs/roadmap/cycles");
    expect(body).toContain(".claude/agents/chief-engineer.md");
    // List-rendered quality gates land in the validation code block.
    expect(body).toMatch(/```bash\nmake quality-gates\nmake test\n```/);
  });

  it("renders consumer overrides into chief-engineer-blitz SKILL.md", () => {
    writeFileSync(
      join(dir, "darkfactory.yaml"),
      `repo:
  displayName: "Test Repo"
  ownerRepo: "test-org/test-repo"
worktreeRoot: ".scratch/worktrees"
agentCommitterOrg: "test-org"
qualityGates:
  - "make test"
`,
    );
    const r = installSkill({ cwd: dir, skillName: "chief-engineer-blitz" });
    const skillMd = r.files.find((f) => f.relTarget === "SKILL.md");
    const body = readFileSync(skillMd!.absoluteTarget, "utf8");
    expect(body).toContain("Local** — Test Repo");
    expect(body).toContain("test-org/test-repo");
    expect(body).toContain(".scratch/worktrees");
    expect(body).toContain("claude-code+<handle>@test-org.ai");
  });

  it("re-installing with identical inputs is a no-op (action=unchanged)", () => {
    installSkill({ cwd: dir, skillName: "chief-engineer-review" });
    const r2 = installSkill({ cwd: dir, skillName: "chief-engineer-review" });
    expect(r2.files.every((f) => f.action === "unchanged")).toBe(true);
  });

  it("re-installing with a different consumer config updates files (action=updated)", () => {
    installSkill({ cwd: dir, skillName: "chief-engineer-review" });
    writeFileSync(
      join(dir, "darkfactory.yaml"),
      `repo:
  displayName: "Renamed Repo"
`,
    );
    const r = installSkill({ cwd: dir, skillName: "chief-engineer-review" });
    expect(r.files.every((f) => f.action === "updated")).toBe(true);
    const body = readFileSync(
      r.files.find((f) => f.relTarget === "SKILL.md")!.absoluteTarget,
      "utf8",
    );
    expect(body).toContain("Renamed Repo");
  });

  it("refuses to overwrite a hand-edited file without --force (action=skipped)", () => {
    const r1 = installSkill({ cwd: dir, skillName: "chief-engineer-review" });
    const skillMdPath = r1.files.find((f) => f.relTarget === "SKILL.md")!.absoluteTarget;
    // Strip the GENERATED marker block to simulate a hand-edit (or a
    // pre-template version of the file).
    const handEdited = readFileSync(skillMdPath, "utf8").replace(
      /<!--\s*\n\s+GENERATED by `df skills install [^]*?-->\n?/,
      "",
    );
    writeFileSync(skillMdPath, handEdited);
    const r2 = installSkill({ cwd: dir, skillName: "chief-engineer-review" });
    const skipped = r2.files.find((f) => f.relTarget === "SKILL.md");
    expect(skipped?.action).toBe("skipped");
    expect(skipped?.reason).toMatch(/hand-edited or pre-template/);
  });

  it("with force=true overwrites a hand-edited file", () => {
    const r1 = installSkill({ cwd: dir, skillName: "chief-engineer-review" });
    const skillMdPath = r1.files.find((f) => f.relTarget === "SKILL.md")!.absoluteTarget;
    writeFileSync(skillMdPath, "hand edited content");
    const r2 = installSkill({
      cwd: dir,
      skillName: "chief-engineer-review",
      force: true,
    });
    const updated = r2.files.find((f) => f.relTarget === "SKILL.md");
    expect(updated?.action).toBe("updated");
    const body = readFileSync(skillMdPath, "utf8");
    expect(body).toContain("GENERATED by `df skills install");
  });

  it("throws on an unknown skill name", () => {
    expect(() =>
      installSkill({ cwd: dir, skillName: "not-a-real-skill" }),
    ).toThrow(/unknown skill/);
  });

  it("respects a custom targetDir (used by the MCP tool's tests)", () => {
    const custom = mkdtempSync(join(tmpdir(), "df-install-target-"));
    try {
      const r = installSkill({
        cwd: dir,
        skillName: "chief-engineer-review",
        targetDir: custom,
      });
      const skillMd = r.files.find((f) => f.relTarget === "SKILL.md")!;
      expect(skillMd.absoluteTarget.startsWith(custom)).toBe(true);
      expect(existsSync(join(custom, "SKILL.md"))).toBe(true);
    } finally {
      rmSync(custom, { recursive: true, force: true });
    }
  });
});

describe("listBundledSkills", () => {
  it("returns every bundled skill in sorted order", () => {
    const items = listBundledSkills();
    const names = items.map((i) => i.name);
    expect(new Set(names)).toEqual(new Set(KNOWN_SKILLS));
    // sorted alphabetically — chief-engineer-blitz < chief-engineer-review
    expect(names).toEqual([...names].sort());
  });

  it("each entry carries a non-empty summary", () => {
    for (const item of listBundledSkills()) {
      expect(item.summary.length).toBeGreaterThan(0);
      expect(item.version).toMatch(/^\d+\.\d+\.\d+/);
    }
  });
});

describe("resolveSkillsRoot — bundled source-of-truth dir", () => {
  it("resolves to the skills/ directory at the package root", () => {
    const root = resolveSkillsRoot();
    expect(existsSync(root)).toBe(true);
    const subdirs = readdirSync(root, { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => d.name)
      .sort();
    for (const skill of KNOWN_SKILLS) {
      expect(subdirs).toContain(skill);
    }
  });
});
