// `df skills install <name>` — install a bundled skill into the consumer's
// `.claude/skills/<name>/`, rendering all template files against the
// consumer's `darkfactory.yaml`.
//
// Idempotency contract:
//   - Re-running `df skills install <name>` overwrites the rendered files
//     (no merge — the rendered file is a generated artifact).
//   - If the rendered file would change AND it has been hand-edited since
//     the last install (detected via a top-of-file GENERATED header marker),
//     install refuses to overwrite without `--force`.
//   - The generated header carries a hash of the manifest version + the
//     resolved variable set, so a no-op re-run is detectable.
//
// Discovery:
//   - The bundled skill source-of-truth lives at `packages/cli/skills/<name>/`
//     in this repo; published, it lives at the equivalent location inside the
//     installed npm package.
//   - `resolveSkillSourceDir()` finds the dir relative to this module's
//     compiled location (works for both src/ in dev and dist/ in production).

import {
  createHash,
} from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  loadDarkFactoryConfig,
  resolveSkillOverrides,
  type DarkFactoryConfig,
  type LoadedDarkFactoryConfig,
} from "./config.js";
import {
  extractReferencedVariables,
  renderTemplateBody,
  type SkillManifest,
} from "./template.js";

/**
 * Names of the skills bundled with this CLI. Adding a new skill = (1) drop
 * the source-of-truth dir under `skills/`, (2) append the name here.
 */
export const KNOWN_SKILLS: ReadonlyArray<string> = [
  "chief-engineer-review",
  "chief-engineer-blitz",
  "objectives",
  "verify",
];

/**
 * The HTML-comment marker emitted at the top of every rendered file
 * (after frontmatter for SKILL.md, at the very top for other files). Used
 * to detect hand-edits at re-install time so we can refuse to overwrite
 * unless `--force` is passed.
 */
const GENERATED_MARKER = "GENERATED by `df skills install";

export interface InstallOptions {
  /** Consumer repo root. `darkfactory.yaml` is loaded from here. */
  readonly cwd: string;
  /** Skill name (must be in KNOWN_SKILLS). */
  readonly skillName: string;
  /**
   * Override location of the target install dir. Defaults to
   * `<cwd>/.claude/skills/<skillName>/`. Tests override to a temp dir.
   */
  readonly targetDir?: string;
  /** Force-overwrite hand-edited rendered files. */
  readonly force?: boolean;
  /** Override the bundled-skills source dir (tests). */
  readonly _sourceRoot?: string;
}

export interface InstalledFile {
  readonly relTarget: string;
  readonly absoluteTarget: string;
  readonly action: "created" | "updated" | "unchanged" | "skipped";
  /** Present when action = "skipped" — explains why. */
  readonly reason?: string;
}

export interface InstallResult {
  readonly skillName: string;
  readonly manifestVersion: string;
  readonly configPath: string;
  readonly configIsDefault: boolean;
  readonly resolvedVariables: ReadonlyArray<{ readonly name: string; readonly value: string }>;
  readonly files: ReadonlyArray<InstalledFile>;
}

export interface ListedSkill {
  readonly name: string;
  readonly version: string;
  readonly summary: string;
  readonly originatingRepo?: string;
}

/**
 * Resolve the absolute path of the bundled-skills source-of-truth root.
 * In dev (running from src/), the path is `<package>/skills/`. In a
 * published install (running from dist/), the path is the same — the
 * `files` array in package.json carries the `skills/` dir verbatim and
 * `dist/skills/index.js`'s ../../skills resolution lands on it.
 */
export function resolveSkillsRoot(): string {
  const here = dirname(fileURLToPath(import.meta.url));
  // src/skills/install.ts → ../../skills (two up: skills → src → package root)
  // dist/skills/install.js → ../../skills (same depth)
  return resolve(here, "..", "..", "skills");
}

function readManifest(skillName: string, sourceRoot: string): SkillManifest {
  const manifestPath = join(sourceRoot, skillName, "skill.json");
  if (!existsSync(manifestPath)) {
    throw new Error(
      `df skills install: unknown skill "${skillName}" — no manifest at ${manifestPath}. Known skills: ${KNOWN_SKILLS.join(", ")}.`,
    );
  }
  const raw = readFileSync(manifestPath, "utf8");
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (err) {
    throw new Error(
      `df skills install: skill.json for "${skillName}" is not valid JSON — ${(err as Error).message}`,
    );
  }
  // Light structural check — full schema is in skills/skill-schema.json.
  // We rely on the renderer's per-variable check (catches typos) and the
  // file-write loop (catches missing files); a heavyweight zod parse is
  // overkill for a directory we author + ship ourselves.
  const m = parsed as Record<string, unknown>;
  if (typeof m.name !== "string" || typeof m.version !== "string") {
    throw new Error(
      `df skills install: skill.json for "${skillName}" missing required fields (name, version).`,
    );
  }
  if (m.name !== skillName) {
    throw new Error(
      `df skills install: skill.json#name "${String(m.name)}" does not match directory name "${skillName}".`,
    );
  }
  if (!Array.isArray(m.files) || m.files.length === 0) {
    throw new Error(
      `df skills install: skill.json#files for "${skillName}" must be a non-empty array.`,
    );
  }
  if (typeof m.variables !== "object" || m.variables === null) {
    throw new Error(
      `df skills install: skill.json#variables for "${skillName}" must be an object.`,
    );
  }
  return parsed as SkillManifest;
}

/**
 * List every bundled skill (one-entry per dir under the source root that
 * has a valid skill.json). Used by `df skills list` + `df_skills_list`.
 */
export function listBundledSkills(sourceRoot?: string): ListedSkill[] {
  const root = sourceRoot ?? resolveSkillsRoot();
  if (!existsSync(root)) return [];
  const out: ListedSkill[] = [];
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const name = entry.name;
    const manifestPath = join(root, name, "skill.json");
    if (!existsSync(manifestPath)) continue;
    try {
      const m = JSON.parse(readFileSync(manifestPath, "utf8")) as SkillManifest;
      const item: ListedSkill = {
        name: m.name,
        version: m.version,
        summary: m.summary,
        ...(m.originatingRepo !== undefined
          ? { originatingRepo: m.originatingRepo }
          : {}),
      };
      out.push(item);
    } catch {
      // Skip malformed manifests so a single bad dir doesn't break the list.
    }
  }
  // Stable order — alphabetical by name, regardless of FS readdir order.
  out.sort((a, b) => a.name.localeCompare(b.name));
  return out;
}

/**
 * Read an existing rendered file, if it exists, and return the marker line
 * embedded by a previous install (if any) so we can detect hand-edits.
 */
function detectExistingMarker(absPath: string): { present: boolean; hash: string | null } {
  if (!existsSync(absPath)) return { present: false, hash: null };
  const body = readFileSync(absPath, "utf8");
  // Marker shape: `# install-hash: <64-hex>` on a line by itself, after the
  // GENERATED prefix line. We match the hash specifically; if the hash isn't
  // present (or doesn't match the freshly-computed one), we treat the file
  // as hand-edited.
  const match = body.match(/install-hash:\s*([0-9a-f]{64})/);
  if (match) return { present: true, hash: match[1] ?? null };
  // Marker comment present but no hash → also treat as old format / hand-edited.
  if (body.includes(GENERATED_MARKER)) return { present: true, hash: null };
  return { present: false, hash: null };
}

/**
 * Compute a stable hash of (manifest.version + resolved-variables) so a
 * re-render with identical inputs produces an identical hash. Embedded in
 * the GENERATED header so subsequent installs can skip a no-op rewrite.
 */
function computeInstallHash(
  manifest: SkillManifest,
  resolved: ReadonlyArray<{ readonly name: string; readonly value: string }>,
): string {
  const h = createHash("sha256");
  h.update(manifest.name);
  h.update("\n");
  h.update(manifest.version);
  h.update("\n");
  // Sort for determinism — renderTemplateBody returns in template-encounter
  // order but the hash should not depend on which template referenced the
  // variable first.
  const sorted = [...resolved].sort((a, b) => a.name.localeCompare(b.name));
  for (const entry of sorted) {
    h.update(entry.name);
    h.update("=");
    h.update(entry.value);
    h.update("\n");
  }
  return h.digest("hex");
}

/**
 * Inject the GENERATED marker (with install-hash) into a rendered body.
 * For .md files with YAML frontmatter, the marker goes immediately after
 * the closing `---`. For other files, it goes at the top.
 */
function injectInstallMarker(
  body: string,
  skillName: string,
  installHash: string,
): string {
  const marker = [
    `<!--`,
    `  ${GENERATED_MARKER} ${skillName}\`. Do not hand-edit.`,
    `  install-hash: ${installHash}`,
    `  Re-render with: df skills install ${skillName}`,
    `  Or edit darkfactory.yaml + the upstream template, then re-install.`,
    `-->`,
    ``,
  ].join("\n");
  // Detect YAML frontmatter (--- ... ---) at file start.
  if (body.startsWith("---\n")) {
    const closing = body.indexOf("\n---", 4);
    if (closing !== -1) {
      const afterFm = closing + "\n---".length;
      const head = body.slice(0, afterFm);
      const tail = body.slice(afterFm);
      // Ensure exactly one blank line between frontmatter and marker.
      const tailTrim = tail.replace(/^\n+/, "");
      return `${head}\n\n${marker}${tailTrim}`;
    }
  }
  return `${marker}${body}`;
}

/**
 * Strip a previously-injected marker block from a body so we can compare
 * the freshly-rendered body to the on-disk body modulo the marker (which
 * carries a hash that changes per-install).
 */
function stripInstallMarker(body: string): string {
  // The marker block is a `<!-- … -->` whose first content line starts with
  // the GENERATED prefix. Conservative match — only the first such block.
  const re = /<!--\s*\n\s+GENERATED by `df skills install [^]*?-->\n?/;
  return body.replace(re, "");
}

/**
 * Install one skill into the consumer's `.claude/skills/<name>/`.
 */
export function installSkill(options: InstallOptions): InstallResult {
  const sourceRoot = options._sourceRoot ?? resolveSkillsRoot();
  const skillSourceDir = join(sourceRoot, options.skillName);
  if (!existsSync(skillSourceDir) || !statSync(skillSourceDir).isDirectory()) {
    throw new Error(
      `df skills install: unknown skill "${options.skillName}". Known skills: ${KNOWN_SKILLS.join(", ")}.`,
    );
  }
  const manifest = readManifest(options.skillName, sourceRoot);

  // Load consumer config + resolve overrides.
  const loaded: LoadedDarkFactoryConfig = loadDarkFactoryConfig(options.cwd);
  const config: DarkFactoryConfig = loaded.config;
  const overrides = resolveSkillOverrides({ config, repoRoot: options.cwd });

  const targetDir =
    options.targetDir ??
    resolve(options.cwd, ".claude", "skills", options.skillName);

  // First pass: render all files in-memory to compute the install hash
  // from the full resolved-variable set across templates (so the hash
  // changes when ANY variable resolves differently, not just one).
  const renderedNoMarker: Array<{ target: string; body: string; substituted: ReadonlyArray<{ name: string; value: string }> }> = [];
  const allVars = new Map<string, string>();
  for (const fileSpec of manifest.files) {
    const templatePath = join(skillSourceDir, fileSpec.template);
    if (!existsSync(templatePath)) {
      throw new Error(
        `df skills install: template file missing at ${templatePath} (skill: ${manifest.name}).`,
      );
    }
    const raw = readFileSync(templatePath, "utf8");
    // Lint: every variable referenced must be declared.
    for (const varName of extractReferencedVariables(raw)) {
      if (!(varName in manifest.variables)) {
        throw new Error(
          `df skills install: template ${fileSpec.template} references undeclared variable "{{${varName}}}" — add to skill.json#variables for skill "${manifest.name}".`,
        );
      }
    }
    const rendered = renderTemplateBody(raw, { manifest, overrides });
    for (const entry of rendered.substituted) {
      allVars.set(entry.name, entry.value);
    }
    renderedNoMarker.push({
      target: fileSpec.target,
      body: rendered.body,
      substituted: rendered.substituted,
    });
  }
  const resolvedVariables = Array.from(allVars, ([name, value]) => ({ name, value }));
  const installHash = computeInstallHash(manifest, resolvedVariables);

  // Second pass: inject marker + write to disk.
  const files: InstalledFile[] = [];
  for (const r of renderedNoMarker) {
    const absTarget = resolve(targetDir, r.target);
    const finalBody = injectInstallMarker(r.body, manifest.name, installHash);
    const existing = detectExistingMarker(absTarget);
    const exists = existsSync(absTarget);

    if (exists && existing.present === false) {
      // File exists but has no marker → hand-edited or pre-template version.
      if (!options.force) {
        files.push({
          relTarget: r.target,
          absoluteTarget: absTarget,
          action: "skipped",
          reason:
            "file exists without GENERATED marker (hand-edited or pre-template). Re-run with --force to overwrite.",
        });
        continue;
      }
    }
    if (exists && existing.present && existing.hash === installHash) {
      // Hash matches → same manifest version + same resolved vars. Compare
      // the body (modulo the marker) to detect a hand-edit the hash cannot
      // catch: a user can edit the prose without touching the marker, and
      // both `manifest.version` + the resolved-variable set stay identical,
      // so the recomputed `installHash` still matches. Without this guard
      // the next install silently treats the modified body as "unchanged"
      // and the consumer drifts from the source-of-truth template.
      const currentBody = readFileSync(absTarget, "utf8");
      const currentWithoutMarker = stripInstallMarker(currentBody).trim();
      const newWithoutMarker = stripInstallMarker(finalBody).trim();
      if (currentWithoutMarker === newWithoutMarker) {
        files.push({
          relTarget: r.target,
          absoluteTarget: absTarget,
          action: "unchanged",
        });
        continue;
      }
      if (!options.force) {
        files.push({
          relTarget: r.target,
          absoluteTarget: absTarget,
          action: "skipped",
          reason:
            "rendered file body has been hand-edited (install-hash matches but content differs from the upstream template). Re-run with --force to overwrite.",
        });
        continue;
      }
    }

    mkdirSync(dirname(absTarget), { recursive: true });
    writeFileSync(absTarget, finalBody, "utf8");
    files.push({
      relTarget: r.target,
      absoluteTarget: absTarget,
      action: exists ? "updated" : "created",
    });
  }

  return {
    skillName: manifest.name,
    manifestVersion: manifest.version,
    configPath: loaded.configPath,
    configIsDefault: loaded.isDefault,
    resolvedVariables,
    files,
  };
}
